const CLOUDFLARE_COLO_LABELS: Readonly<Record<string, string>> = Object.freeze({
  AKL: "Auckland, New Zealand",
  AMS: "Amsterdam, Netherlands",
  ARN: "Stockholm, Sweden",
  ATL: "Atlanta, United States",
  BKK: "Bangkok, Thailand",
  BLR: "Bengaluru, India",
  BOM: "Mumbai, India",
  BRU: "Brussels, Belgium",
  BUD: "Budapest, Hungary",
  CDG: "Paris, France",
  CGK: "Jakarta, Indonesia",
  CPT: "Cape Town, South Africa",
  DEL: "Delhi, India",
  DEN: "Denver, United States",
  DFW: "Dallas, United States",
  DUB: "Dublin, Ireland",
  DXB: "Dubai, United Arab Emirates",
  EWR: "Newark, United States",
  EZE: "Buenos Aires, Argentina",
  FRA: "Frankfurt, Germany",
  GVA: "Geneva, Switzerland",
  HEL: "Helsinki, Finland",
  HKG: "Hong Kong",
  HYD: "Hyderabad, India",
  IAD: "Ashburn, United States",
  ICN: "Seoul, South Korea",
  IST: "Istanbul, Türkiye",
  JNB: "Johannesburg, South Africa",
  KIX: "Osaka, Japan",
  KUL: "Kuala Lumpur, Malaysia",
  LAS: "Las Vegas, United States",
  LAX: "Los Angeles, United States",
  LHR: "London, United Kingdom",
  LIS: "Lisbon, Portugal",
  MAA: "Chennai, India",
  MAD: "Madrid, Spain",
  MEL: "Melbourne, Australia",
  MEX: "Mexico City, Mexico",
  MNL: "Manila, Philippines",
  MRS: "Marseille, France",
  NRT: "Tokyo, Japan",
  ORD: "Chicago, United States",
  OSL: "Oslo, Norway",
  OTP: "Bucharest, Romania",
  PRG: "Prague, Czechia",
  SAN: "San Diego, United States",
  SCL: "Santiago, Chile",
  SEA: "Seattle, United States",
  SIN: "Singapore",
  SJC: "San Jose, United States",
  SOF: "Sofia, Bulgaria",
  SYD: "Sydney, Australia",
  TLV: "Tel Aviv, Israel",
  TPE: "Taipei, Taiwan",
  VIE: "Vienna, Austria",
  WAW: "Warsaw, Poland",
  YUL: "Montreal, Canada",
  YYZ: "Toronto, Canada",
  ZRH: "Zurich, Switzerland",
});

export function describeCloudflareColo(colo: string): string {
  const normalized = colo.trim().toUpperCase();
  if (!normalized || normalized === "UNKNOWN") return "unknown";

  const label = CLOUDFLARE_COLO_LABELS[normalized];
  return label ? `${normalized} (${label})` : normalized;
}
